<a href="https://colab.research.google.com/github/kusumaboddeti2004/22A81A0572/blob/main/DA_day2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing
import numpy as np

In [ ]:
k=np.eye(4,8)
print(k)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]


In [ ]:
k=np.array([[1,2,3,4,5,6,7,8],[2,5,6,7,8,3,4,5],[4,6,1,2,3,4,5,6],[3,4,6,3,6,2,5,6]])
print(k)

[[1 2 3 4 5 6 7 8]
 [2 5 6 7 8 3 4 5]
 [4 6 1 2 3 4 5 6]
 [3 4 6 3 6 2 5 6]]


Random variable(rand)

In [ ]:
b=np.random.rand(1)
print(b)

[0.56408661]


In [ ]:
a=np.random.rand(8,4)
print(a)          #rand-range between 0 and 1

[[0.0482606  0.96331173 0.33206083 0.10928942]
 [0.53900433 0.97386345 0.5795641  0.88439165]
 [0.06539076 0.26319053 0.81871017 0.92725739]
 [0.85142118 0.0688397  0.08971989 0.47015742]
 [0.80762871 0.31201149 0.0933997  0.72799338]
 [0.04068334 0.81518328 0.12598889 0.02152372]
 [0.11664397 0.55849076 0.61597126 0.64989842]
 [0.80568831 0.5412309  0.52939279 0.6691749 ]]


Splitting

In [ ]:
a=np.arange(1,33).reshape(8,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
np.vsplit(a,(3,6))

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(a,(3,6)) #split at 3r and after 6r

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
a=np.arange(1,33).reshape(4,8)
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(a,4)

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(a,(3,6))

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27]]),
 array([[ 4,  5,  6],
        [12, 13, 14],
        [20, 21, 22],
        [28, 29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

Trignomatric Functions

In [ ]:
np.pi

3.141592653589793

In [ ]:
A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
np.rad2deg(A)

array([ 45.,  60.,  90., 180.])

In [ ]:
a=[45,60,90,180]
np.deg2rad(a)

array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [ ]:
np.sin(1) #radians

0.8414709848078965

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(1)

1.5574077246549023

In [ ]:
st=np.array([1,2,3,4,5,7,8])


In [ ]:
np.mean(st)

4.285714285714286

In [ ]:
np.median(st)

4.0

In [ ]:
np.std(st)

2.3733211036908783

In [ ]:
np.var(st)

5.63265306122449

In [ ]:
c=np.arange(1,5).reshape(2,2)
print(c)

[[1 2]
 [3 4]]


In [ ]:
c=10*np.random.rand(24).reshape(6,4)
print(c)

[[8.17958492 4.28120305 9.40678143 5.9473721 ]
 [4.653453   7.62932547 4.00361237 5.69609649]
 [7.7432786  8.6987924  0.54662311 1.74728119]
 [5.37572969 7.51209134 1.51991606 2.43750895]
 [5.99901497 3.45361865 0.73211248 3.83864956]
 [9.88102888 0.33367666 0.53378868 0.36730548]]


In [ ]:
print(np.argmax(c))

2


In [ ]:
print(np.argmax(c,axis=1))

[2 1 1 1 0 0]


In [ ]:
print(np.argmax(c,axis=0))

[5 2 0 0]


In [ ]:
print(np.argmin(c))

21


In [ ]:
print(np.argmin(c,axis=0))

[1 5 5 5]


In [ ]:
print(np.argmin(c,axis=1))

[1 2 2 2 2 1]


Searching

In [ ]:
a=np.array([18,8,7,19,86,99])
print(np.where(a%2==0))

(array([0, 1, 4]),)


In [ ]:
a=np.array([-9,-7,-8,0,6,8,9])
print(np.where(a%2==0))

(array([2, 3, 4, 5]),)


In [ ]:
a=np.array([24,16,7,17,54,60])
print(np.where(a%6==0))

(array([0, 4, 5]),)


In [ ]:
a=np.array([1,2,3,4,5,6]) #only for sorted list
b=np.searchsorted(a,3)
print(b)

2


Sorting Array

In [ ]:
#sorting array
a=np.array(["kusuma","kaveri","veena"])
print(np.sort(a))

['kaveri' 'kusuma' 'veena']


In [ ]:
a=np.array([False,True,False,True])
print(np.sort(a))

[False False  True  True]


In [ ]:
#2d sort-sorting happens with in rows
a=np.array([[6,5,4],[3,2,1]])
print(np.sort(a))

[[4 5 6]
 [1 2 3]]


Array Filters

In [ ]:
a=np.array([20,45,60,78,9,23])
f=np.where(a%2==0)
print(f)

(array([0, 2, 3]),)


In [ ]:
a[f]

array([20, 60, 78])

Iterating Through arrays

In [ ]:

names=np.array(["Kusuma","Kaveri","Veena","Sadha","Varsha","Teju","Lorry"])
initial=np.array(["B","T","J","M","V","E","Y"])
for i,j in zip(initial,names):
  print(i,".",j)

B . Kusuma
T . Kaveri
J . Veena
M . Sadha
V . Varsha
E . Teju
Y . Lorry


In [ ]:
a1=np.array([3,5,6,4,7])
a2=np.array([6,7,8,9,4])
n=np.multiply(a1,a2)
print(n)

[18 35 48 36 28]


In [ ]:
a1=np.array([3,5,6,4,7])
a2=np.array([6,7,8,9,4])
n=np.divide(a1,a2)
print(n)

[0.5        0.71428571 0.75       0.44444444 1.75      ]


In [ ]:
a1=np.array([3,5,6,4,7])
a2=np.array([6,7,8,9,4])
n=np.mod(a1,a2)
print(n)

[3 5 6 4 3]


In [ ]:
a1=np.array([3,5,6,4,7])
a2=np.array([6,7,8,9,4])
n=np.divmod(a1,a2)
print(n)

(array([0, 0, 0, 0, 1]), array([3, 5, 6, 4, 3]))


Logarithms

In [ ]:
a=1.2
print(np.log(a)) #natural logarithm log e

0.1823215567939546


In [ ]:
a=1.2
print(np.log2(a)) #log base 2

0.2630344058337938


In [ ]:
a=1.2
print(np.log10(a)) #log base 10

0.07918124604762482


In [ ]:
a=np.array([1.2,3.5,2,4.5])
print(np.log2(a))

[0.26303441 1.80735492 1.         2.169925  ]


Other Mathematical Functions

In [ ]:
a1=np.array([5,7,9,10])
a=np.cumsum(a1)
print(a)

[ 5 12 21 31]


In [ ]:
a1=np.array([2,6,5,4])
a=np.cumprod(a1)
print(a)

[  2  12  60 240]


In [ ]:
a1=np.array([5,6,9,10])
a=np.diff(a1)           # 6-5=1
print(a)                # 9-6=3
                        # 10-9=1

[1 3 1]


In [ ]:
a=35
b=24
c=np.lcm(a,b)
print(c)

840


In [ ]:
a=35
b=24
c=np.gcd(a,b)
print(c)

1


In [ ]:
a=np.array([12,24,15,30])
gc=np.gcd.reduce(a)
print(gc)


3


In [ ]:
a=np.array([12,24,15,30])
gc=np.lcm.reduce(a)
print(gc)


120
