<a href="https://colab.research.google.com/github/kusumaboddeti2004/22A81A0572/blob/main/DA_day1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing
import numpy as np


Arrays


In [ ]:
#Creating 1D array
A=np.array([1,2,3,4])
print(type(A))

<class 'numpy.ndarray'>


In [ ]:
#Creating a 2D array #rows and columns 1.parent[] then 2 rows
B=np.array([[3,5,7],[3,6,8]])
print(B)

[[3 5 7]
 [3 6 8]]


In [ ]:
#creating 3D array - rows,columns,groups
C=np.array([[[1,2,3],[14,5,6]],[[7,6,4],[2,4,9]]])
print(C)

[[[ 1  2  3]
  [14  5  6]]

 [[ 7  6  4]
  [ 2  4  9]]]


In [ ]:
#checking dimensions
print(A.ndim)
print(B.ndim)
print(C.ndim)

1
2
3


In [ ]:
#ones 3-rows,2-columns
d=np.ones((3,2))
print(d)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#ones 2-groups,3-rows,2-colomn
d=np.ones((2,3,2))
print(d)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
#zeros
d=np.zeros((3,2))
print(d)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#zeros
d=np.zeros((2,3,2))
print(d)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
e=np.eye(4,3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
#identity matrix
e=np.eye(4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#arange
H=np.arange(2,31,3) #start,stop,step
print(H)


[ 2  5  8 11 14 17 20 23 26 29]


In [ ]:
#arange
H=np.arange(2,31,3).reshape(10,1)
print(H)

[[ 2  5  8 11 14]
 [17 20 23 26 29]]


In [ ]:
f=np.arange(5,1001,5)
print(f)

[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
   75   80   85   90   95  100  105  110  115  120  125  130  135  140
  145  150  155  160  165  170  175  180  185  190  195  200  205  210
  215  220  225  230  235  240  245  250  255  260  265  270  275  280
  285  290  295  300  305  310  315  320  325  330  335  340  345  350
  355  360  365  370  375  380  385  390  395  400  405  410  415  420
  425  430  435  440  445  450  455  460  465  470  475  480  485  490
  495  500  505  510  515  520  525  530  535  540  545  550  555  560
  565  570  575  580  585  590  595  600  605  610  615  620  625  630
  635  640  645  650  655  660  665  670  675  680  685  690  695  700
  705  710  715  720  725  730  735  740  745  750  755  760  765  770
  775  780  785  790  795  800  805  810  815  820  825  830  835  840
  845  850  855  860  865  870  875  880  885  890  895  900  905  910
  915  920  925  930  935  940  945  950  955  960  965  970  975  980
  985 

In [ ]:
#linespace //in between 12 and 20 having 6 numbers including 12 and 20
import numpy as np
V=np.linspace(12,20,6) # 1 1+0.2---- 2(there are 6 elements and the 6 elements have the same difference)
print(V)

[12.  13.6 15.2 16.8 18.4 20. ]


In [ ]:
L=np.arange(1,9).reshape(2,4)
print(L)
P=np.arange(2,10).reshape(2,4)
print(P)

[[1 2 3 4]
 [5 6 7 8]]
[[2 3 4 5]
 [6 7 8 9]]


In [ ]:
#adition of two matrices
K=(L+P)
print(K)

[[ 3  5  7  9]
 [11 13 15 17]]


In [ ]:
#sum of the numbers in above matrix
j=np.sum((L,P))
print(j)

80


In [ ]:
s=np.sum((L,P),axis=0)
print(s)              #add 1+2=3 ,5+6=11----(1 matrix column is added to 2 matrix column )

[[ 3  5  7  9]
 [11 13 15 17]]


In [ ]:
s=np.sum((L,P),axis=1)
print(s)

[[ 6  8 10 12]
 [ 8 10 12 14]]


In [ ]:
s=np.sum((L,P),axis=2)
print(s)

[[10 26]
 [14 30]]


In [ ]:
g=np.ones((4,2))
h=np.ones((4,2))
print(np.sum((g,h),axis=0))

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]


In [ ]:
g=np.ones((4,2))
h=np.ones((4,2))
print(np.sum((g,h),axis=1))

[[4. 4.]
 [4. 4.]]


In [ ]:
g=np.ones((4,2))
h=np.ones((4,2))
print(np.sum((g,h),axis=2))

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [ ]:
b=np.array([25,289,361,81])
for i in b:
  print(int(np.sqrt(i)),"square is",i)




5 square is 25
17 square is 289
19 square is 361
9 square is 81


In [ ]:
a=np.array([1,2,3,4,5,7])
a.resize(2,3)
b=np.array([6,7,5,9,2,5])
b.resize(2,3)
print(np.vstack((a,b)))
print("\n")
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 7]
 [6 7 5]
 [9 2 5]]


[[1 2 3 6 7 5]
 [4 5 7 9 2 5]]


In [ ]:
a=np.array([1,2,3,4,5,7])
a.resize(2,3)
b=np.array([6,7,5,9,2,5])
b.resize(2,3)
print(a)
print(b)

[[1 2 3]
 [4 5 7]]
[[6 7 5]
 [9 2 5]]


In [ ]:
#dstack
a=np.arange(30).reshape(2,3,5) #0 and 15 will group upto 4 and 19(1), then 5 & 20 to 9 & 24(2) then 10 &25 to 14 & 29(3)  rows=groups,colurs=no.of rows in each column
print(a)
print("output of dstack")
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
output of dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]
